# Generated by Django 3.0.3 on 2020-12-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='to_top',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
